[project]
name = "dfp-bookstore"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=5.2.7",
    "django-allauth>=65.13.0",
    "django-crispy-forms>=2.4",
    "psycopg2-binary>=2.9.11",
]
